// <auto-generated />
using System;
using Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Persistencia.Migraciones
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20231016214738_AddForeignKeyPlaylist")]
    partial class AddForeignKeyPlaylist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aplicacion.Dominio.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Playlist");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd84c892-c3c3-4e29-a9d5-26c1dc2ae249"),
                            Nombre = "Playlist 1"
                        },
                        new
                        {
                            Id = new Guid("32ca83ae-f15a-4253-8632-e519de605e1f"),
                            Nombre = "Playlist 2"
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdPlaylist")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdPlaylist");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d25e2e67-c89c-4ace-94fd-4a7c494b3a38"),
                            Duracion = 100,
                            Nombre = "Song 1"
                        },
                        new
                        {
                            Id = new Guid("5c48d210-95d0-4475-ab87-d41c0c29edd2"),
                            Duracion = 200,
                            Nombre = "Song 2"
                        },
                        new
                        {
                            Id = new Guid("2d02110e-ff4f-4f0a-a320-7c3b07a0f5ab"),
                            Duracion = 300,
                            Nombre = "Song 3"
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Song", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Playlist", "Playlist")
                        .WithMany("Songs")
                        .HasForeignKey("IdPlaylist");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
